### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by khairalanam** [khairalanam/GPRG#2]
The current readme is just a Nextjs-generated readme and has to be updated. The readme has to include these sections (not in order):
* Small introduction
* Setup documentation (must include commands to set up the project)
* contributing guide (keep it short) and should link to CONTRIBUTING.md
* tech stack used

You may include other sections as you wish but the above four must be included.

**Comment by babitarit** [comment]
i wanted to work on it pls assign me this issue

**Comment by khairalanam** [comment]
That's great! I would suggest first setup the project and running it in your local system. It's not entirely complete (just the markdown rendering part is remaining), but the majority of the project should run fine.
