### ISSUE TITLE
Change the navigation bar on mobile view

### ISSUE THREAD

**Issue by khairalanam** [khairalanam/GPRG#3]
The current navigation bar on the mobile view is just the same as the desktop view except smaller. I would like this navigation bar to be a hamburger menu.
* The navigation bar has to be smooth on opening the menu and closing the menu, i.e., use transitions.
* The navigation bar has to cover the entire mobile viewport with a dark background in low opacity.
* The icons for hamburger and "X" must either be used from react-icons or can be done using plain CSS.

**Comment by nayakswadhin** [comment]
Hii @khairalanam I want to work on this issue can you please guide me how to run this in local machine as i have tried it with Gitpod but it did not work and i am not able to fork this repo!!

**Comment by nayakswadhin** [comment]
Hi @khairalanam I want to work on this issue can you please assign it to me??

**Comment by khairalanam** [comment]
Hi @nayakswadhin! That's great! I will assign rn.

**Comment by nayakswadhin** [comment]
Heyy @khairalanam , I have created a PR on this issue. Kindly review it.

**Comment by khairalanam** [comment]
That's great! Please check PR as I have requested some changes to be done.

Also, please send screenshots of the hamburger menu. If possible, a screen record is even better.
