### ISSUE TITLE
Handle the errors and inputs for the main form

### ISSUE THREAD

**Issue by khairalanam** [khairalanam/GPRG#6]
The main form doesn't have any kind of indication to know whether a certain input is handling valid input or not, or whether a certain input is required or not. Here are some of the things you can work on:
* Certain fields are considered required and there are some fields that are multiple in number but only some of them are required. If a user doesn't fill these inputs and tries to submit the form, it has to be alerted by indicating in red which fields are required.
* There are many fields that handle certain types of inputs like numbers and links. The user has to give the correct input and has to be alerted in case the user provides an invalid input. For instance, if a user provides a number for an input that only accepts links, then it has to be alerted just under the input that the user must provide a link.

**Comment by Smitkhobragade** [comment]
Assign this to me. i can do it.

**Comment by khairalanam** [comment]
That's awesome @Smitkhobragade! I will assign this to you.

**Comment by Smitkhobragade** [comment]
hi @khairalanam . While working on the project I found profile-readme>page.tsx is empty so i am not getting any output and the soln to check the input. so can you tell me what was there in the the file

**Comment by khairalanam** [comment]
Actually, I am still working on the page. I am trying to convert the mdx file (present in mdx > ProfileReadme.mdx) to plain markdown and display it in the profile-readme > page.tsx. I have raised an issue for this in case anyone can work on it :D.

**Comment by Smitkhobragade** [comment]
Ok . Till that time i will remove the navigation and after validation is done. i will put it back onto the place.

**Comment by khairalanam** [comment]
Okay great.

**Comment by Smitkhobragade** [comment]
@khairalanam I have raised the PR about this issue. you can review and merge it.

**Comment by khairalanam** [comment]
Sure thing :)
